config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('scm.urls')),
    path('',include('im.urls')),
    path('',include('crm.urls')),
    path('',include('statModul.urls')),
]

crm/urls.py
#basic libraries
from django.urls import path

#import 
from crm.views.client.views import clientList, clientCreate,clientEdit,clientDelete
from crm.views.sale.views import saleList, saleInicia,saleEdit,saleDelete,saleCreate,saleGetData,saleItemView,saleItemDelete,salepdfPrint,saleNew,saleLast,saleCreateNew
from crm.views.quote.views import quoteList, quoteInicia,quoteEdit,quoteDelete,quoteCreate,quoteGetData,quoteItemView,quoteItemDelete,quotepdfPrint,quoteNew,quoteLast
from crm.views.devolution.views import devolutionList, devolutionEdit, devolutionDelete, devolutionCreate,devolutionInicia,devolutionItemView,devolutionGetData,devolutionItemDelete,devpdfPrint,devolutionNew


app_name='crm'
urlpatterns=[
        path('client/list',clientList,name='clientList'),
        path('client/create',clientCreate,name='clientCreate'),
        path('client/edit/<int:pk>/',clientEdit, name='clientEdit'),
        path('client/delete/<int:pk>/',clientDelete,name='clientDelete'),

        path('sale/list',saleList,name='saleList'),
        path('sale/new',saleNew,name='saleNew'),
        path('sale/create/<int:sale_id>/',saleCreate,name='saleCreate'),
        path('sale/inicia',saleInicia,name='saleInicia'),
        path('sale/getdata',saleGetData,name='saleGetData'),
        path('sale/edit/<int:pk>/',saleEdit, name='saleEdit'),
        path('sale/delete/<int:pk>/',saleDelete,name='saleDelete'),

        path('sale/itemview',saleItemView,name='saleItemView'),
        path('sale/itemdelete/<int:pk>/',saleItemDelete,name='saleItemDelete'),
        path('sale/pdfprint/<int:pk>/',salepdfPrint,name='pdfPrint'),
        path('sale/last',saleLast,name='saleLast'),

        
        path('sale/createnew/',saleCreateNew,name='saleCreateNew'),
       
        path('quote/list',quoteList,name='quoteList'),
        path('quote/new',quoteNew,name='quoteNew'),
        path('quote/create/<int:quote_id>/',quoteCreate,name='quoteCreate'),
        path('quote/inicia',quoteInicia,name='quoteInicia'),
        path('quote/getdata',quoteGetData,name='quoteGetData'),
        path('quote/edit/<int:pk>/',quoteEdit, name='quoteEdit'),
        path('quote/delete/<int:pk>/',quoteDelete,name='quoteDelete'),

        path('quote/itemview',quoteItemView,name='quoteItemView'),
        path('quote/itemdelete/<int:pk>/',quoteItemDelete,name='quoteItemDelete'),
        path('quote/pdfprint/<int:pk>/',quotepdfPrint,name='pdfPrint'),
        path('quote/last',quoteLast,name='quoteLast'),





        path('devolution/list',devolutionList,name='devolutionList'),
        path('devolution/new',devolutionNew,name='devolutionNew'),
        path('devolution/edit/<int:pk>/',devolutionEdit, name='devolutionEdit'),
        path('devolution/delete/<int:pk>/',devolutionDelete,name='devolutionDelete'),
        path('devolution/create',devolutionCreate,name='devolutionCreate'),
        path('devolution/inicia',devolutionInicia,name='devolutionInicia'),
        path('devolution/itemview',devolutionItemView,name='devolutionItemView'),
        path('devolution/getdata',devolutionGetData,name='devolutionGetData'),

        path('devolution/itemdelete/<int:pk>/',devolutionItemDelete,name='devolutiuonItemDelete'),
        path('devolution/pdfprint/<int:pk>/',devpdfPrint,name='devpdfPrint'),
        ]

im/urls.py
#basic libraries
from django.urls import path

#import 
from im.views.category.views import categoryList, categoryCreate,categoryEdit,categoryDelete
from im.views.product.views import productList, productCreate,productEdit,productDelete


app_name='im'
urlpatterns=[
        path('category/list',categoryList,name='categoryList'),
        path('category/create',categoryCreate,name='categoryCreate'),
        path('category/edit/<int:pk>/',categoryEdit, name='categoryEdit'),
        path('category/delete/<int:pk>/',categoryDelete,name='categoryDelete'),

        path('product/list',productList,name='productList'),
        path('product/create',productCreate,name='productCreate'),
        path('product/edit/<int:pk>/',productEdit, name='productEdit'),
        path('product/delete/<int:pk>/',productDelete,name='productDelete'),
        ]

crm/forms.py
from django.forms import ModelForm
from crm.models import Client,Sale,Devolution,Quote

class clientForm(ModelForm):
    class Meta:
        model = Client 
        fields = '__all__'

class saleForm(ModelForm):
    class Meta:
        model = Sale 
        fields = '__all__'

class quoteForm(ModelForm):
    class Meta:
        model = Quote 
        fields = '__all__'


class devolutionForm(ModelForm):
    class Meta:
        model =Devolution 
        fields = '__all__'

crm/views/client/views.py
#basic libraries
from django.shortcuts import render, redirect, get_object_or_404

#import 
from crm.models import Client 
from crm.forms import clientForm 


def clientList(request):
    data = {
            'client_create':'/client/create',
            'title' : 'Listado clients',
            'clients' : Client.objects.all(),
            'entity':'clients',
            'url_create':'/client/create',
            }
    return render(request, 'client/list.html', data)

def clientCreate(request):
    data = {
            'title':'client Create',
            'form':clientForm,
            'entity':'clients',
            'retornoLista':'/client/list',
            }
    if request.method == 'POST':
        form = clientForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect ( '/client/list',data)
        else:
            print(form)
            print("invalid form")
            print(form.errors)
            return render(request, 'client/create.html',{'form':form})

    else:
        return render(request, 'client/create.html',data)
        
def clientEdit(request,pk):
    client=get_object_or_404(Client,id=pk)
    if request.method != 'POST':
        form=clientForm(instance=client)
    else:
        form = clientForm(request.POST,instance=client)
        if form.is_valid():
            form.save()
            return redirect ( '/client/list')
    context={
            'form':form,
            'title' : 'client Edit',
            'entity':'clientes',
            'retornoLista':'/client/list',
            } 
    return render(request, 'client/edit.html',context) 

def clientDelete(request,pk):
    client=Client.objects.get(id=pk)
    if request.method == 'POST':
        client.delete()
        return redirect ( '/client/list')

    context = {
            'item':client,
            'title' : 'client Delete',
            'entity':'clientes',
            'retornoLista':'/client/list',
            }
    return render(request,  'client/delete.html',context)

crm/views/devolution/views.py
#basic libraries
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse,HttpResponse
import json
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.decorators.csrf import csrf_exempt

#import 
from crm.models import Devolution,devolutionItem,Client,Product,devolutionItem
from crm.forms import devolutionForm

@csrf_exempt
def devolutionList(request):
    data = {
            'entityUrl':'/devolution/new',
            'devolution_create':'/devolution/create',
            'title' : 'Devoluciones',
            'devolutions' : Devolution.objects.all(),
            'entity':'Crear Nuevo',
            'url_create':'/devolution/create',
            'url_js':'/static/lib/java/devolution/list.js',
            'btnId':'btnOrderList',
            'home':'home'
            }
 
    return render(request, 'devolution/list.html', data)

@csrf_exempt
def devolutionEdit(request,pk):
    devolution=get_object_or_404(Devolution,id=pk)
    if request.method != 'POST':
        form=devolutionForm(instance=devolution)
    else:
        form = devolutionForm(request.POST,instance=devolution)
        if form.is_valid():
            form.save()
            return redirect ( '/devolution/list')
    context={
            'form':form,
            'title' : 'devolution Edit',
            'entity':'devolutiones',
            'retornoLista':'/devolution/list',
            } 
    return render(request, 'devolution/edit.html',context) 

@csrf_exempt
def devolutionDelete(request,pk):
    devolution=Devolution.objects.get(id=pk)
    if request.method == 'POST':
        devolution.delete()
        return redirect ( '/devolution/list')

    context = {
            'item':devolution,
            'title' : 'devolution Delete',
            'entity':'devolutiones',
            'retornoLista':'/devolution/list',
            }
    return render(request,  'devolution/delete.html',context)

@csrf_exempt
def devolutionCreate(request):
    devolution=Devolution.objects.last()
    items=devolution.devolutionitem_set.all()
    context={
            'url_js':'/static/lib/java/devolution/create.js',
            'items':items,
            'total':devolution,
            'returnList':'/devolution/list',
            'returnCreate':'/devolution/new'
            }
    return render(request, 'devolution/create.html',context)

@csrf_exempt
def devolutionInicia(request):
    if request.method == "POST":
        call=json.loads(request.body)
        clienteId=int(call['id'])
        monedero=call['monedero']
        client=Client.objects.get(id=clienteId)
        devolution=Devolution.objects.create(client=client,monedero=monedero)
        devolution.save()
        return JsonResponse('devolucion Registrada',safe=False)

@csrf_exempt
def devolutionGetData(request):
    if request.method == 'POST':
        call= json.loads(request.body)
        pk=call['id']
        qs=Product.objects.get(barcode=pk)
        devolution=Devolution.objects.last()
        name = [qs.id,qs.name,qs.priceLista]
        return JsonResponse({'datos':name},safe=False)

@csrf_exempt
def devolutionItemView(request):
    if request.method == "POST":
        data = json.loads(request.body)
        devolution=Devolution.objects.last()
        pk=int(data[0])
        quantity=data[1]
        print(pk)
        print()
        product=Product.objects.get(id=pk)
        cost=product.costo
        if product.granel == True and float(quantity) >= float(product.minimo):
            margen=product.margen
        elif float(quantity) < float(product.minimo):
            margen=product.margenGranel
        else:
            margen=product.margen
        
        stockActual=(Product.objects.get(id=pk)).stock
#        if float(quantity) > stockActual:
#            return JsonResponse('No hay stock suficiente', safe=False)
        itemsdevolution=devolution.devolutionitem_set.all()
        outputlist=list(filter(lambda x:x.product.id==pk,itemsdevolution))
        print(stockActual)
        if outputlist:
            repetido=outputlist[0]
            quantity=int(repetido.quantity)+int(quantity)
            devolutionItem.objects.filter(id=repetido.id).delete()
            devolutionItem.objects.create(product=product,devolution=devolution,quantity=quantity,cost=cost,margen=margen)
            return JsonResponse('se sumaron',safe=False)
        else:
            devolutionItem.objects.create(product=product,devolution=devolution,quantity=quantity,cost=cost,margen=margen)
            return JsonResponse('creo nuevo registro',safe=False)

@csrf_exempt
def devolutionItemDelete(request,pk):
    item=devolutionItem.objects.get(id=pk)
    if request.method == 'POST':
        item.delete()
        return redirect ( '/devolution/create')
    context = {
            'item':item,
            'title' : 'item Delete',
            'entity':'orders',
            'retornoLista':'/devolution/list',
            }
    return render(request,  'devolution/delete.html',context)

@csrf_exempt
def devpdfPrint(request,pk):
    devolution=Devolution.objects.get(id=pk)
    items=devolution.devolutionitem_set.all()
    data={
            "devolution":devolution,
            "devolutionId":devolution.id,
            "items":items,
            "cliente":devolution.client.name
            }
    template_path = 'devolution/pdfprint.html'
    context = data
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="devolution.pdf"'
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

@csrf_exempt
def devolutionNew(request):
    data = {

            'devolution_create':'/devolution/create',
            'entityUrl':'/devolution/list',
            'title' : 'Devoluciones',
            'devolutions' : Devolution.objects.all(),
            'entity':'Lista devolutions',
            'url_create':'/devolution/create',
            'url_js':'/static/lib/java/devolution/list.js',
            'btnId':'btnOrderList',
            'home':'home',
            'newBtn':'Devolucion',
            }
 
    return render(request, 'devolution/new.html', data)

crm/templates/sale/create.html
{% extends 'create.html' %}

{% block columns %}
    <tr>
        <th scope="col">Quantity</th>
        <th scope="col">Description</th>
        <th scope="col">P.Unit</th>
        <th scope="col">P.total</th>
        <th scope="col">Options</th>
    </tr>
{% endblock %}

{% block rows %}
    {% for p in items%}
    <tr id="item-{{p.id}}">
            <td>{{ p.quantity}}</td>
            <td>{{ p.product}}</td>
            <td>{{ p.precioUnitario|floatformat:3}}</td>
            <td>{{ p.get_total|floatformat:2}}</td>
            <td>
		    <a href="#"  class="btn btn-danger btn-xs btn-flat  deleteButton" data-item-id="{{p.id}}">
                            <i class="fas fa-trash-alt"></i>Delete</a> 
            </td>
        </tr>
    {% endfor %}
{% endblock %}

crm/templates/sale/createnew.html
{% extends 'salecreatenew.html' %}
{% block columns %}
    <tr>
        <th scope="col">BarCode</th>
        <th scope="col">Name</th>
        <th scope="col">Marca</th>
        <th scope="col">Price</th>
        <th scope="col">PriceGranel</th>
	<!-- <th scope="col">Opciones</th> -->
    </tr>
{% endblock %}

{% block rows %}
    {% for c in products%}
        <tr>
            <td>{{ c.barcode}}</td>
            <td>{{ c.name }}</td>
            <td>{{ c.brand}}</td>
            <td>${{ c.priceLista}}</td>
            <td>$ {{ c.priceListaGranel}}</td>
<!--            <td>
                    <a href="/product/edit/{{c.id}}" class="btn btn-warning btn-xs btn-flat">
                        <i class="fas fa-edit"></i></a>
              
                    <a href="/product/delete/{{c.id}}" class="btn btn-danger btn-xs btn-flat">
                            <i class="fas fa-trash-alt"></i></a>
</td> -->
        </tr>
    {% endfor %}
{% endblock %}

crm/templates/sale/delete.html
{% extends 'crud.html' %}
{% block campos%}

<p>Are you sure you want to delete "{{item}}"?</p>

<form method="POST">

        {% csrf_token %}
        <a href="{%url 'crm:saleCreate'%}" class="btn btn-primary">Cancel</a>
         <button  type="submit" class="btn btn-danger">Confirm</button>
</form>
{% endblock %}

crm/templates/sale/list.html
{% extends 'list.html' %}

{% block columns %}
    <tr>
        <th scope="col">Id</th>
        <th scope="col">Cliente</th>
        <th scope="col">Monedero</th>
        <th scope="col">Importe</th>
        <th scope="col">Fecha</th>
        <th scope="col">Opciones</th>
    </tr>
{% endblock %}

{% block rows %}
    {% for o in sales %}
        <tr>
            <td>{{ o.id }}</td>
            <td>{{ o.client }}</td>
            <td>{{ o.monedero }}</td>
            <td>$ {{ o.get_cart_total|floatformat:2 }}</td>
            <td>{{ o.date_created }}</td>
            <td>
<!--                <a href="/sale/edit/{{ o.id }}" class="btn btn-warning btn-xs btn-flat">
                    <i class="fas fa-edit"></i>
</a> 
                <a href="/sale/delete/{{ o.id }}" class="btn btn-danger btn-xs btn-flat">
                    <i class="fas fa-trash-alt"></i>
                </a>
		-->
                <a href="/sale/pdfprint/{{ o.id }}" class="btn btn-secondary btn-xs btn-flat">
                    <i class="fas fa-print"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
{% endblock %}

crm/templates/sale/new.html
{% extends 'new.html' %}

{%block botones%}

<div class="form-group">
   <label for="clientId">Seleccionar cliente</label>
    <select class="form-select" id="clientId" name="clientId">
        <option value="">Seleccione un cliente</option>
        {% for client in clients %}
	<option value="{{ client.id }}" >{{client.name}}</option>
        {% endfor %}
    </select>
    <small class="form-text text-muted">Seleccione un cliente existente. Cliente por defecto: "Mostrador".</small>
</div>
 


<div class="form-group">
<select class="form-select" aria-label="Default select example" id="btnMonedero">
  <option value="0">No monedero</option>
  <option value="1">compra con  monedero</option>
</select>
</div>

{%endblock%}
{%block lastBotones%}
<div class="card-footer">
		<a href="/sale/last" class="btn btn-success btn-flat" id="{{btnId}}">
			<i class="fas fa-folder-open"></i>Ultima Venta</a>
        </div>
{%endblock%}

{% block dateFilter %}
<div class="card-footer">
    <!-- Date Filter Form -->
    <form method="get" action="{% url 'crm:saleList' %}" class="mt-3 d-flex align-items-center">
        <label for="start_date" class="me-2">Fecha Inicial: </label>
        <input type="date" id="start_date" name="start_date" value="{{ start_date|default_if_none:'' }}" class="form-control me-2" style="width: auto;">
        
        <label for="end_date" class="me-2">Fecha Final:  </label>
        <input type="date" id="end_date" name="end_date" value="{{ end_date|default_if_none:'' }}" class="form-control me-2" style="width: auto;">
        
        <button type="submit" class="btn btn-primary">Filtrar </button>
    </form>
</div>
{% endblock %}

crm/templates/sale/pdfprint.html
{%extends 'pdfprint.html'%}

{%block cabecera%}
    <div class="row">
        <div class="col-12">
    		<div class="invoice-title">
                <h5>Ferretería León Tulancingo</h5><h6 class="text-left">Folio Venta: {{sale.id}}</h6><h6 class="text-left">Fecha: {{sale.date_created}}</h6>

    		</div>
    		<hr>
    		<div class="row">
    			<div class="col-3 small" >
    				<address>
    					Calle fresnos lote 7 mz.23, cp.43685<br>
    					Col.San   Juan,  Tulancingo  Hidalgo<br>
                        Tel.celular  y  whatsapp: 7751423616<br>
    					Telefono: 7751423616
    				</address>
    			</div>
                <div class="col-3">
    				<address>
    				</address>
    			</div>
                <div class="col-3">
    				<address>
    				</address>
    			</div>
    			<div class="col-3 text-left small">
    				<address>
        			<strong>Datos de cliente</strong><br>
                    Nombre: {{sale.client.name}}<br>
                    Telefono: {{sale.client.phoneNumber}}<br>
    				</address>
    			</div>
    		</div>
    </div>
</div>
 
{%endblock%}

{%block detalle%}
{%for item in items%}
            <tr>
                <td>{{item.product.id}}</td>
                <td class="text-lowercase">{{item.product.name}}</td>
                <td class="text-center">$ {{item.precioUnitario}}</td>
                <td class="text-center">{{item.quantity}}</td>
		<td class="text-right">$ {{item.get_total|floatformat:2}}</td>
            </tr>
{%endfor%}
            <tr>
                <td class="no-line"></td>
                <td class="no-line"></td>
                <td class="no-line"></td>
                <td class="no-line text-center"><strong>Total</strong></td>
                <td class="no-line text-right"><strong>$ {{sale.get_cart_total}}</strong></td>
            </tr>
{%endblock%}